export interface Player {
    "position_txt": string,
    "weight"?: string,
    "name_display_first_last": string,
    "college"?: string,
    "height_inches"?: string,
    "starter_sw"?: string,
    "jersey_number": string,
    "end_date"?: string,
    "name_first"?: string,
    "bats"?: string,
    "team_code"?: string,
    "height_feet"?: string,
    "pro_debut_date"?: string,
    "status_code"?: string,
    "primary_position": string,
    "birth_date"?: string,
    "team_abbrev"?: string,
    "throws"?: string,
    "team_name"?: string,
    "name_display_last_first"?: string,
    "name_use"?: string,
    "player_id": string,
    "name_last"?: string,
    "team_id"?: string,
    "start_date"?: string,
    "name_full"?: string
}