export interface Transaction {
        "trans_date_cd"?: string,
        "from_team_id"?: string,
        "orig_asset"?: string,
        "final_asset_type"?: string,
        "player"?: string,
        "resolution_cd"?: string,
        "final_asset"?: string,
        "name_display_first_last"?: string,
        "type_cd"?: string,
        "name_sort"?: string,
        "resolution_date"?: string,
        "conditional_sw"?: string,
        "team"?: string,
        "type"?: string,
        "name_display_last_first"?: string,
        "transaction_id"?: string,
        "trans_date"?: string,
        "effective_date"?: string,
        "player_id"?: string,
        "orig_asset_type"?: string,
        "from_team"?: string,
        "team_id"?: string,
        "note": string,
}